WebPage8/Models/Category.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace WebPage8.Models
{
    public class Category
    {
        [Key]
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string BrandUrl { get; set; }
        public string Description { get; set; }        
        public List<Computer> Computers { get; set; }
    }
}

WebPage8/Models/Computer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WebPage8.Models
{
    public class Computer
    {
        [Key]
        public int ComputerId { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Processor { get; set; }
        public string RAM { get; set; }
        public string HardDisk { get; set; }
        public string SystemType { get; set; }
        public string PenAndTouch { get; set; }
        public string ImageUrl { get; set; }
        public int CategoryId { get; set; }
        public Category Category { get; set; }
        public List<Review> Reviews { get; set; }
        public List<ComputerOrder> ComputerOrders { get; set; }
    }
}

WebPage8/Models/ComputerOrder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WebPage8.Models
{
    public class ComputerOrder
    {
        [Key]
        public int ComputerOrderId { get; set; }
        public int Quantity { get; set; }
        public int ComputerId { get; set; }
        public Computer Computer { get; set; }
        public int OrderId { get; set; }      
        public Order Order { get; set; }
    }
}

WebPage8/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WebPage8.Models
{
    public class Customer
    {
        [Key]
        public int CustomerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string PostalCode { get; set; }
        public string Street { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public List<Order> Orders { get; set; }
        public List<Review> Reviews { get; set; }
    }
}

WebPage8/Models/ErrorViewModel.cs
using System;

namespace WebPage8.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebPage8/Models/Order.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WebPage8.Models
{
    public class Order
    {
        [Key]
        public int OrderId { get; set; }
        public DateTime OrderPlaced { get; set; }
        public DateTime OrderFullfilled { get; set; }
        public int CustomerId { get; set; }        
        public Customer Customer { get; set; }
        public List<ComputerOrder> ComputerOrders { get; set; }        
        
    }
}

WebPage8/Models/Review.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace WebPage8.Models
{
    public class Review
    {
        [Key]
        public int ReviewId { get; set; }
        public string Text { get; set; }
        public string Rating { get; set; }
        public int ComputerId { get; set; }
        public Computer Computer { get; set; }
        public int CustomerId { get; set; }
        public Customer Customer { get; set; }         
    }
}

WebPage8/ViewModels/CategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPage8.Models;

namespace WebPage8.ViewModels
{
    public class CategoryViewModel
    {
        public List<Category> Categories = new List<Category>();
        public string Search { get; set; }
    }
}

WebPage8/ViewModels/ComputerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPage8.Models;

namespace WebPage8.ViewModels
{
    public class ComputerViewModel
    {
        public List<Computer> Computers { get; set; }
        public Computer Computer { get; set; }
        public List<Category> Categories { get; set; }
        public string Search { get; set; }

    }
}

WebPage8/ViewModels/CreateCategoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebPage8.ViewModels
{
    public class CreateCategoryViewModel
    {
    }
}

WebPage8/ViewModels/CreateComputerViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebPage8.ViewModels
{
    public class CreateComputerViewModel
    {

    }
}

WebPage8/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPage8.Services;
using WebPage8.ViewModels;

namespace WebPage8.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IComputerService _computerService;
        public CategoryController(ICategoryService categoryService, IComputerService computerService)
        {
            _categoryService = categoryService;
            _computerService = computerService;
        }
        public IActionResult Index(CategoryViewModel categoryViewModel)
        {
            if (!string.IsNullOrEmpty(categoryViewModel.Search))
            {
                return View("ViewItems", _categoryService.FindBy(categoryViewModel));
            }
            else
            {
                return View(_categoryService.All());
            }          
        }

        public IActionResult Details(ComputerViewModel category)
        {
            return View("Details", _computerService.FindBy(category));
        }
    }
}

WebPage8/Controllers/ComputerController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebPage8.Data;
using WebPage8.Services;
using WebPage8.ViewModels;

namespace WebPage8.Controllers
{
    public class ComputerController : Controller
    {
        private readonly IComputerService _computerService;
        public ComputerController(IComputerService computerService)
        {
            _computerService = computerService;
        }
        public IActionResult Index(ComputerViewModel computerViewModel)
        {
            if(!string.IsNullOrEmpty(computerViewModel.Search))
            {
                return View(_computerService.FindBy(computerViewModel));
            }
            else
            {
                return View(_computerService.All());
            }            
        }
        public IActionResult Details(int id)
        {
            return View("Details",_computerService.FindBy(id));
        }
    }
}

WebPage8/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebPage8.Services;
using WebPage8.ViewModels;

namespace WebPage8.Controllers
{
    public class HomeController : Controller
    {

        private readonly ICategoryService _categoryService;
        public HomeController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }
        public IActionResult Index(CategoryViewModel categoryViewModel)
        {
            if (!string.IsNullOrEmpty(categoryViewModel.Search))
            {
                return View("BrandItems", _categoryService.FindBy(categoryViewModel));
            }
            else
            {
                return View(_categoryService.All());
            }
        }
    }
}

WebPage8/Views/Category/Index.cshtml
@model CategoryViewModel
@{
    ViewBag.Title = "Computer Web Shop | Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section headerSection {
    @Html.Partial("_LayoutHeader")
}
<partial name="_Search.cshtml" model="@Model" />
<partial name="_Carousel.cshtml" />
<section>
    <div class="container sectionspc">
        <div class="hpanel forum-box">
            <div class="row product-container">
                @foreach (Category category in Model.Categories)
                {
                    <partial name="_Items.cshtml" model="category" />
                }
            </div>
        </div>
    </div>
</section>

WebPage8/Views/Category/_BrandItems.cshtml
@model CategoryViewModel


@section headerSection {
    @Html.Partial("_LayoutProductHeader")

}
<link href="@Url.Content("~/styles/slider.css")" rel="stylesheet" />
<script src="@Url.Content("~/Scripts/bootstrap-slider.js")"></script>

<section>
    <div class="container">
        <div class="col-md-4 col-sm-4">
            <div class="seller-leftbox text-center">
                <b>€ 10</b> <input id="ex2" type="text" class="span2" value="" data-slider-min="10" data-slider-max="1000" data-slider-step="5" data-slider-value="[250,450]" /> <b>€ 1000</b>
            </div>
            @*<div class="seller-leftbox text-center">
                    <div class="img-circlebig"> <img src="@Url.Content("~/images/brand/dell.png")" id="imgPhoto" class="img-circle m-b" alt="logo"></div>
                    <div class="stats-label text-color"> <span id="spnDisplayTitle" class="font-extra-bold font-uppercase"></span></div>

                    <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span>
                    <p class="p-m">
                        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text<br />

                    </p>
                    <p class="p-m">
                        <span id="spnDescription">
                            <br />
                            <small></small>
                        </span>
                    </p>

                </div>*@



        </div>

        <div class="col-md-8 col-sm-8">
            <div class="col-md-12 col-sm-6" style="padding-bottom: 10px;"> <img src="@Url.Content("~/images/sam-small.png")" class="img-responsive"> </div>
            <div class="row product-container">
                <div onclick="@("window.location.href='" + @Url.Action("Detail", "Product") + "'");" class="col-lg-6 col-sm-8">
                    <div class="hpanel">
                        <div class="panel-body no-padding poluritm">
                            <div class="entry-thumbnailsmall"> <img src="@Url.Content("~/images/pro2.png")" class="img-responsive"> </div>
                            <div class="p-sm productdetail">
                                <h4>Item Title</h4>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>

                            </div>
                        </div>
                    </div>
                </div>
                <div onclick="@("window.location.href='" + @Url.Action("Detail", "Product") + "'");" class="col-lg-6 col-sm-8">
                    <div class="hpanel">
                        <div class="panel-body no-padding poluritm">
                            <div class="entry-thumbnailsmall"> <img src="@Url.Content("~/images/pro2.png")" class="img-responsive"> </div>
                            <div class="p-sm productdetail">
                                <h4>Item Title</h4>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                @*<h4 class="text-success"> $1 206,40</h4>*@
                            </div>
                        </div>
                    </div>
                </div>
                <div onclick="@("window.location.href='" + @Url.Action("Detail", "Product") + "'");" class="col-lg-6 col-sm-8">
                    <div class="hpanel">
                        <div class="panel-body no-padding poluritm">
                            <div class="entry-thumbnailsmall"> <img src="@Url.Content("~/images/pro2.png")" class="img-responsive"> </div>
                            <div class="p-sm productdetail">
                                <h4>Item Title</h4>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                @*<h4 class="text-success"> $1 206,40</h4>*@
                            </div>
                        </div>
                    </div>
                </div>

                <div onclick="@("window.location.href='" + @Url.Action("Detail", "Product") + "'");" class="col-lg-6 col-sm-8">
                    <div class="hpanel">
                        <div class="panel-body no-padding poluritm">
                            <div class="entry-thumbnailsmall"> <img src="@Url.Content("~/images/pro2.png")" class="img-responsive"> </div>
                            <div class="p-sm productdetail">
                                <h4>Item Title</h4>
                                <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry.</p>
                                @*<h4 class="text-success"> $1 206,40</h4>*@
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</section>
<script>
    $(document).ready(function () {
        //alert("show")
        $("#ex2").slider({});

        // Without JQuery
        //var slider = new Slider('#ex2', {});
    });
</script>

WebPage8/Views/Category/_Carousel.cshtml
<div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
    <div class="carousel-caption">
        <div class="container">
            <div class="col-lg-12">
                <div class="col-sm-7 hpanel m-t-md  homesearch">
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel items -->
    <div class="carousel-inner">
        <div class="active item"><img src="@Url.Content("~/images/top1.png")" /></div>
        <div class="item"><img src="@Url.Content("~/images/top2.jpg")" /></div>
        <div class="item"><img src="@Url.Content("~/images/top1.png")" /></div>
    </div>
</div>

WebPage8/Views/Category/_Items.cshtml
@model Category

<div class="col-lg-4 col-sm-6">
    <div class="hpanel">
        <div class="panel-body no-padding">
            <div class="entry-thumbnail"> 
                <img src="@Model.BrandUrl" class="img-responsive" alt=""> 
            </div>
            <div class="p-sm productdetail">
                <h3>@Model.Name</h3>
                <p>@Model.Description </p>
                <h4 class="text-success"> no.of items 1 206,40</h4>
                <div class="btn btn-default btn-sm">
                    4.4 <i class="fa fa-star" aria-hidden="true"></i> (78)
                </div>
                <button type="button" onclick="@("window.location.href='" + @Url.Action("BrandItems", "Product") + "'");" class="btn btn-success btn-sm pull-right">Köp</button>
            </div>
        </div>
    </div>
</div>

WebPage8/Views/Category/_ProductList.cshtml
<section id="feat-seller-container">
	<div class="container p-lg">
		<div class="row">
			<h2 class="text-center"> Popular Products</h2>
			<p class="text-center font24">Popular <span style="color:#85cb15">Products</span> </p>
				<div class="col-md-12">
					<div class="owl-carousel owl-theme">
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro1.png" data-holder-rendered="true">
											</a>
										</div>
										<div class="media-body">
											<h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
										</div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
							
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro2.png" data-holder-rendered="true">
											</a>
										</div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                        </div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
									
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro3.jpg" data-holder-rendered="true">
											</a>
										</div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                        </div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
						
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro1.png" data-holder-rendered="true">
											</a>
										</div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                        </div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
									@*<div class="col-sm-8"> <i class="fa fa-map-marker" aria-hidden="true"></i> 68 5th Avenue New York</div>*@
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro2.png" data-holder-rendered="true">
												
											</a>
										</div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                        </div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
							
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
						<div class="item">
							<div class="hpanel">
								<div class="panel-body">
									<div class="media">
										<div class="media-left">
											<a href="#">
												<img alt="64x64" class="media-object" data-src="holder.js/64x64" style="width: 64px;
             height: 64px;" src="~/images/pro2.png" data-holder-rendered="true">
											</a>
										</div>
                                        <div class="media-body">
                                            <h4 class="media-heading">Product Title </h4>
                                            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry</p>
                                        </div>
									</div>
								</div>
								<div class="panel-footer pull-left width100">
							
									<div class="col-sm-4"> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span> </div>
								</div>
							</div>
						</div>
					</div>
				</div>
			
		</div>
	</div>
</section>

WebPage8/Views/Category/_Search.cshtml
@model CategoryViewModel
<form asp-controller="Category" asp-action="Index" method="post">
    <div class="col-lg-12" @*style="margin-top:10px!important"*@>
        <div class="d-flex justify-content-between">
            <div class="input-group panel-body no-padding">
                <input asp-for="@Model.Search" class=" form-control " type="text" placeholder="What are you looking for?">
                <span class="input-group-btn">
                    <input type="submit" class="btn btn-primary2 btn-lg p-sm" value="Sök" />
                </span>
            </div>
        </div>
    </div>
</form>
  

WebPage8/Views/Category/bck_OldIndex.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebPage8/Views/Computer/Details.cshtml
@model Computer
<form asp-controller="Computer" asp-action="Details" method="post">
    <h1>Enter Computer id:</h1>
    <input asp-for="@Model.ComputerId" name="id" />
    <input type="submit" value="send" />
</form>
<div>

    <h1>@Model.Name</h1>
    <h2>@Model.SystemType</h2>
    <h3>@Model.Price</h3>
</div>

WebPage8/Views/Computer/Index.cshtml
@model ComputerViewModel

@foreach(var computer in Model.Computers)
            {
<div>
    <h2>@computer.Name</h2>
    <h3>@computer.Price</h3>
    <h4>@computer.SystemType</h4>
    <h4>@computer.Category.Name</h4>
</div>
            
}

WebPage8/Views/Home/Index.cshtml
@model CategoryViewModel

@{
    ViewBag.Title = "Computer Web Shop | Home";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section headerSection {
    @Html.Partial("_LayoutHeader")
}

<form asp-controller="Category" asp-action="Index" method="post">
    <div class="col-lg-12" @*style="margin-top:10px!important"*@>
        <div class="d-flex justify-content-between">
            <div class="input-group panel-body no-padding">
                <input asp-for="@Model.Search" class=" form-control " type="text" placeholder="What are you looking for?">
                <span class="input-group-btn">
                    <input type="submit" class="btn btn-primary2 btn-lg p-sm" value="Sök" />
                </span>
            </div>
        </div>
    </div>
</form>

<div>
    <div id="carousel" class="carousel slide carousel-fade" data-ride="carousel">
        <div class="carousel-caption">
            <div class="container">
                <div class="col-lg-12">
                    <div class="col-sm-7 hpanel m-t-md  homesearch">
                    </div>
                </div>
            </div>
        </div>
        <!-- Carousel items -->
        <div class="carousel-inner">
            <div class="active item"><img src="@Url.Content("~/images/top1.png")" /></div>
            <div class="item"><img src="@Url.Content("~/images/top2.jpg")" /></div>
            <div class="item"><img src="@Url.Content("~/images/top1.png")" /></div>
        </div>
    </div>

    <section>
        <div class="container sectionspc">
            <div class="hpanel forum-box">
                <div class="row product-container">
                    @foreach (Category category in Model.Categories)
                    {
                        <partial name="_PartialBrands.cshtml" model="category" />
                    }
                </div>
            </div>
        </div>
    </section>

</div>

WebPage8/Views/Home/_PartialBrands.cshtml
@model Category

<div class="col-lg-4 col-sm-6">
    <div class="hpanel">
        <div class="panel-body no-padding">
            <div class="entry-thumbnail">
                <img src="@Model.BrandUrl" class="img-responsive" alt="">
            </div>
            <div class="p-sm productdetail">
                <h3>@Model.Name</h3>
                <p>@Model.Description </p>
                <h4 class="text-success"> no.of items 1 206,40</h4>
                <div class="btn btn-default btn-sm">
                    4.4 <i class="fa fa-star" aria-hidden="true"></i> (78)
                </div>
                <div>
                    <a asp-controller="Computer" asp-action="Details">Välja</a>
                </div>
                </div>
        </div>
    </div>
</div>

WebPage8/Views/Product/Index.cshtml
@{
    ViewBag.Title = "Computer Web Shop | Brands";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section headerSection {
    @*@Html.Partial("_LayoutProductHeader")*@

}


<section>

    <div class="seller-cntr bg-light m-b-lg">
        <div class="seller-profile"> <img id="imgBanner" src="@Url.Content("~/Content/images/top2.jpg")"> </div>
        @*<div class="profile-picture">
            <img id="imgDisplay" src="@Url.Content("~/Content/images/dell.png")" class="img-circle m-b avatar" alt="seller-image">
            <div class=" text-center">
                <div class="text-color h4"> <span class="font-extra-bold font-uppercase " id="txtDisplayTitle"></span></div>
                <div id="idRating">
                    <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star checked"></span> <span class="fa fa-star"></span> <span class="fa fa-star"></span>
                </div>
                <p class="p-m" id="txtDescription"> </p>
            </div>
        </div>*@
    </div>
</section>

@*@Html.Partial("_BrandItems")*@

WebPage8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="~/styles/site.css" />
    <script src="~/scripts/site.js"></script>


</head>
<body class="landing-page">
    <!-- Header -->
    @RenderSection("headerSection", false)
    <div>
        @RenderBody()
    </div>

    <!-- Footer -->
    @Html.Partial("_LayoutFooter")

    @RenderSection("scripts", required: false)


   






</body>
</html>

WebPage8/Views/Shared/_LayoutDetailHeader.cshtml
<nav class="navbar  navbar-top navbar-default" style="background-color: #332538 !important">
    <div class="container">
        <div class="navbar-header">
            <button aria-controls="navbar" aria-expanded="false" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle collapsed" type="button"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
            <a href="@Url.Action("index","home")"><img src="@Url.Content("~/images/logo-small.png")" class="logo" /></a>
        </div>
        <div id="navbar-client" class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right">
                @*<li><a href="#" data-toggle="modal" id="lnkSeller" data-target="#join-seller-model">Become a Seller</a></li>*@
                <li><a href="@Url.Action("AboutUs","home")">Kundtjanst</a></li>
                <li><a href="/Identity/Account/Login">Konto</a></li>
                <li><a href="#" data-toggle="modal" id="lnkLogin" data-target="#login-model">Varukorg</a></li>
                <li><a href="/Identity/Account/Login">Admin</a></li>
                @*<li><a id="lnkJoin" class="navbar-brand" href="#" style="color: #fff !important;" data-toggle="modal" data-target="#join-us-model"> &nbsp; join &nbsp;</a></li>*@
            </ul>
        </div>
    </div>
</nav>
<div class="col-lg-12" >
    <div >
       
            <div class="input-group panel-body no-padding">
                <input class=" form-control " type="text" placeholder="">

                </span> <span class="input-group-btn" style="content: normal !important;">
                    <button type="button" class="btn btn-primary2 btn-lg p-sm">Sök </button>
                </span>
            </div>
      
    </div>
</div>